# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Email: hello.jamie@protonmail.com : uryyb.wnzvr@cebgbaznvy.pbz
# Email: hello.jamie@pm.com : uryyb.wnzvr@cz.pbz
title: Jamie Robertson | full stack developer
email: uryyb.wnzvr@cebgbaznvy.pbz

description: > # this means to ignore newlines until "baseurl:"
  I am a full stack web developer working with Django, Python, Flask API and React JS

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'jamierobertson.github.io' # the base hostname & protocol for your site
static: '/static'

twitter_username: JamieRudeboyson

github_username: github.com/JamieRobertson
github_url: https://github.com/JamieRobertson

linkedin_username: linkedin.com/in/jamie-r
linkedin_url: https://www.linkedin.com/in/jamie-r/  # https://www.linkedin.com/in/jamie-r-36616210/

tel_se: '+46 (0) 76 026 66 42'
tel_uk: '+44 (0) 7881 820 789'

# Other URLs
resume_url: '/resume'

plugins:
  - jekyll-octicons
  - jekyll-redirect-from

exclude: ['gulpfile.js', 'README.md', 'package.json', 'node_modules']

# Sass settings
sass:
    style: compressed
    sass_dir: _sass
    sourcemap: true

# Build settings
markdown: kramdown
comments: true
kramdown:
    input: GFM
    parse_block_html: true
    auto_ids:       false
    enable_coderay: false
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
    enable_coderay: false
    coderay:
        coderay_wrap:              div
        coderay_line_numbers:      inline
        coderay_line_number_start: 1
        coderay_tab_width:         4
        coderay_bold_every:        10
        coderay_css:               style
